// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DispatcherClient is the client API for Dispatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DispatcherClient interface {
	PullJob(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*JobResponse, error)
}

type dispatcherClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatcherClient(cc grpc.ClientConnInterface) DispatcherClient {
	return &dispatcherClient{cc}
}

func (c *dispatcherClient) PullJob(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, "/primes.Dispatcher/PullJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatcherServer is the server API for Dispatcher service.
// All implementations must embed UnimplementedDispatcherServer
// for forward compatibility
type DispatcherServer interface {
	PullJob(context.Context, *PullRequest) (*JobResponse, error)
	mustEmbedUnimplementedDispatcherServer()
}

// UnimplementedDispatcherServer must be embedded to have forward compatible implementations.
type UnimplementedDispatcherServer struct {
}

func (UnimplementedDispatcherServer) PullJob(context.Context, *PullRequest) (*JobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullJob not implemented")
}
func (UnimplementedDispatcherServer) mustEmbedUnimplementedDispatcherServer() {}

// UnsafeDispatcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatcherServer will
// result in compilation errors.
type UnsafeDispatcherServer interface {
	mustEmbedUnimplementedDispatcherServer()
}

func RegisterDispatcherServer(s grpc.ServiceRegistrar, srv DispatcherServer) {
	s.RegisterService(&Dispatcher_ServiceDesc, srv)
}

func _Dispatcher_PullJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherServer).PullJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/primes.Dispatcher/PullJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherServer).PullJob(ctx, req.(*PullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dispatcher_ServiceDesc is the grpc.ServiceDesc for Dispatcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dispatcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "primes.Dispatcher",
	HandlerType: (*DispatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PullJob",
			Handler:    _Dispatcher_PullJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "primes.proto",
}

// FileServerClient is the client API for FileServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServerClient interface {
	FetchSegment(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (FileServer_FetchSegmentClient, error)
}

type fileServerClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServerClient(cc grpc.ClientConnInterface) FileServerClient {
	return &fileServerClient{cc}
}

func (c *fileServerClient) FetchSegment(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (FileServer_FetchSegmentClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileServer_ServiceDesc.Streams[0], "/primes.FileServer/FetchSegment", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileServerFetchSegmentClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileServer_FetchSegmentClient interface {
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type fileServerFetchSegmentClient struct {
	grpc.ClientStream
}

func (x *fileServerFetchSegmentClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileServerServer is the server API for FileServer service.
// All implementations must embed UnimplementedFileServerServer
// for forward compatibility
type FileServerServer interface {
	FetchSegment(*FetchRequest, FileServer_FetchSegmentServer) error
	mustEmbedUnimplementedFileServerServer()
}

// UnimplementedFileServerServer must be embedded to have forward compatible implementations.
type UnimplementedFileServerServer struct {
}

func (UnimplementedFileServerServer) FetchSegment(*FetchRequest, FileServer_FetchSegmentServer) error {
	return status.Errorf(codes.Unimplemented, "method FetchSegment not implemented")
}
func (UnimplementedFileServerServer) mustEmbedUnimplementedFileServerServer() {}

// UnsafeFileServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServerServer will
// result in compilation errors.
type UnsafeFileServerServer interface {
	mustEmbedUnimplementedFileServerServer()
}

func RegisterFileServerServer(s grpc.ServiceRegistrar, srv FileServerServer) {
	s.RegisterService(&FileServer_ServiceDesc, srv)
}

func _FileServer_FetchSegment_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileServerServer).FetchSegment(m, &fileServerFetchSegmentServer{stream})
}

type FileServer_FetchSegmentServer interface {
	Send(*Chunk) error
	grpc.ServerStream
}

type fileServerFetchSegmentServer struct {
	grpc.ServerStream
}

func (x *fileServerFetchSegmentServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

// FileServer_ServiceDesc is the grpc.ServiceDesc for FileServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "primes.FileServer",
	HandlerType: (*FileServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchSegment",
			Handler:       _FileServer_FetchSegment_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "primes.proto",
}

// ConsolidatorClient is the client API for Consolidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsolidatorClient interface {
	PushResult(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*ResultAck, error)
}

type consolidatorClient struct {
	cc grpc.ClientConnInterface
}

func NewConsolidatorClient(cc grpc.ClientConnInterface) ConsolidatorClient {
	return &consolidatorClient{cc}
}

func (c *consolidatorClient) PushResult(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*ResultAck, error) {
	out := new(ResultAck)
	err := c.cc.Invoke(ctx, "/primes.Consolidator/PushResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsolidatorServer is the server API for Consolidator service.
// All implementations must embed UnimplementedConsolidatorServer
// for forward compatibility
type ConsolidatorServer interface {
	PushResult(context.Context, *ResultRequest) (*ResultAck, error)
	mustEmbedUnimplementedConsolidatorServer()
}

// UnimplementedConsolidatorServer must be embedded to have forward compatible implementations.
type UnimplementedConsolidatorServer struct {
}

func (UnimplementedConsolidatorServer) PushResult(context.Context, *ResultRequest) (*ResultAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushResult not implemented")
}
func (UnimplementedConsolidatorServer) mustEmbedUnimplementedConsolidatorServer() {}

// UnsafeConsolidatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsolidatorServer will
// result in compilation errors.
type UnsafeConsolidatorServer interface {
	mustEmbedUnimplementedConsolidatorServer()
}

func RegisterConsolidatorServer(s grpc.ServiceRegistrar, srv ConsolidatorServer) {
	s.RegisterService(&Consolidator_ServiceDesc, srv)
}

func _Consolidator_PushResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsolidatorServer).PushResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/primes.Consolidator/PushResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsolidatorServer).PushResult(ctx, req.(*ResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Consolidator_ServiceDesc is the grpc.ServiceDesc for Consolidator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Consolidator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "primes.Consolidator",
	HandlerType: (*ConsolidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushResult",
			Handler:    _Consolidator_PushResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "primes.proto",
}
